### ISSUE TITLE
Another entry for Tables 2 and 3

### ISSUE THREAD

**Issue by antonisa** [boknilev/nlp-analysis-methods#6]
Our upcoming NAACL paper "Neural Machine Translation of Text from Non-Native Speakers"  [preprint](https://arxiv.org/pdf/1808.06267.pdf) includes adversarial examples for Machine Translation, based on english ungrammatical data from non-native speakers.
In our [github page](https://bitbucket.org/antonis/nmt-grammar-noise) we provide:

1. Gold Spanish translations of the (English) JFLEG corpus, which has both ungrammatical/noisy and corrected sentences.
2. WMT'18 datasets across 7 languages {cs,de,et,fi,ru,tr,zh}-en with English sides injected with specific types of grammatical noise (word/segment level): article, preposition, noun number errors and subject-verb agreement errors. (and a character level one: typo by dropping a single random character)

**Comment by boknilev** [comment]
Looks great, thanks!
 I added this to table 3 as adversarial examples in https://github.com/boknilev/nlp-analysis-methods/commit/ef8e401a8c6076ef9a0321e4f79330ab1163be0c. It's kind of in the interface of adversarial examples and challenge sets, so I can see it also going into table 2. For now, I updated the list in https://github.com/boknilev/nlp-analysis-methods/issues/1.
